name: Deploy Storybook Workflow
on: 
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
jobs:
  deploy-storybook:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install and Build
        run: |
         yarn install --immutable
         yarn build-storybook -o docs-build --docs
 
      - name: Deploy Storybook to GH Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs-build
          target_folder: docs