name: End Workflow
on:
  workflow_run:
    workflows:
      - 'Start Workflow'
    types:
      - completed
  workflow_dispatch:


jobs:
  end:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Do something busy
        timeout-minutes: 10
        run: echo done busy work
      - name: Print End
        run: echo end


