name: End Workflow
on:
  workflow_run:
    workflows:
      - 'Start Workflow'
    types:
      - completed
  workflow_dispatch:


jobs:
  end:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}


      - name: Print End
        run:  sleep 10m; echo  end


