name: End Workflow
on:
  workflow_run:
    workflows:
      - 'Start Workflow'
    types:
      - completed
  workflow_dispatch:


jobs:
  end:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: start
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Print End
        run:  sleep 10m; echo  end


