name: Start Workflow
on: [push, workflow_dispatch]

jobs:
  start:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
          workflow_id: end.yaml
      - name: Print Start
        run: echo start
